### ISSUE TITLE
Error on "bundle exec rake db:schema:load": NoMethodError: undefined method `last_comment' for #< Rake::

### ISSUE THREAD

**Issue by hermann77** [ging/vish#120]
Error on "bundle exec rake db:schema:load": NoMethodError: undefined method `last_comment' for #< Rake::.....

After reading http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11 
my solution was to change Gemfile.lock and to set 'rake' exactly to version 10.5.0. The version 10.5.0 is the last version defines 'last_comment'. 
To make it clear: Gemfile.lock from VISH repository sets the right version (10.5.0) but at some step the file Gemfile.lock was overridden with rake =12.0 

After editing Gemfile.lock: 
_bundle update_
_bundle install_
and finally
_bundle exec rake db:schema:load_

If you have a better solution, welcome. Or an advice how to avoid overriding the Gemfile.lock

Thank you very much.

--
Ubuntu 14.04
MySQL 5.5
VISH master branch

**Comment by agordillo** [comment]
Fixed (by adding gem 'rake', '10.5.0' to Gemfile).

Thanks for your feedback.
